name: 🐛 Bug Report
description: Report a bug or unexpected behavior in AEGIS CLI
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill out the information below to help us diagnose and fix the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these items before submitting your bug report
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have read the documentation and troubleshooting guides
          required: true
        - label: I can reproduce this issue consistently
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Enter input '...'
        3. See error
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened instead
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      options:
        - Linux (Ubuntu/Debian)
        - Linux (RHEL/CentOS/Fedora)
        - Linux (Other)
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Windows 10
        - Windows 11
        - WSL2 (Ubuntu)
        - WSL2 (Other)
        - Other
    validations:
      required: true

  - type: input
    id: aegis-version
    attributes:
      label: AEGIS Version
      description: What version of AEGIS are you using?
      placeholder: "v1.0.0 or commit hash"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using? (if running from source)
      placeholder: "3.11.0"

  - type: input
    id: k8s-version
    attributes:
      label: Kubernetes Version
      description: What version of Kubernetes are you connecting to?
      placeholder: "v1.28.0"

  - type: dropdown
    id: installation
    attributes:
      label: Installation Method
      description: How did you install AEGIS?
      options:
        - Binary download from GitHub releases
        - Built from source
        - Docker container
        - Package manager
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please paste any relevant error messages or logs
      placeholder: Paste error messages, stack traces, or log output here
      render: text

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Please share your AEGIS configuration (remove sensitive information)
      placeholder: Paste your aegis-config.yaml or relevant configuration
      render: yaml

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Screenshots (if applicable)
        - Related issues or discussions
        - Workarounds you've tried
        - Any other relevant information

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing a fix?
      options:
        - label: I would be willing to submit a pull request to fix this issue